[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
  let g:polyglot_disabled = ['latex']  "for vimtex, need to disable latex-box
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  let g:gitgutter_max_signs=500
  let g:gitgutter_map_keys=0  "Disable all key mapping by gitgutter
  if exists('&signcolumn')  "Vim 7.4.2201
    "Always show sign column
    set signcolumn=yes
  else
    let g:gitgutter_sign_column_always=1
  endif
  augroup MyAutoCmd
    autocmd Colorscheme * highlight GitGutterAdd ctermfg=2 guifg=#009900
    autocmd Colorscheme * highlight GitGutterChange ctermfg=3 guifg=#bbbb00
    autocmd Colorscheme * highlight GitGutterDelete ctermfg=1 guifg=#ff2222
  augroup END
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indentLine_fileTypeExclude=['help', 'nerdtree', 'unite']
  let g:indentLine_setConceal = 0
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
  \ 'colorscheme': 'wombat',
  \ 'separator': {'left': '', 'right': ''},
  \ 'subseparator': {'left': '|', 'right': '|'},
  \ 'active': {
  \   'left': [['mode', 'paste'], ['readonly', 'filename', 'modified']],
  \   'right': [['lineinfo', 'percent'], ['fileformat', 'fileencoding', 'filetype']]
  \ },
  \ 'inactive': {
  \   'left': [['filename']],
  \   'right': [['lineinfo', 'percent']]
  \ },
  \ 'component_function': {
  \   'mode': 'LightLineMode'
  \ }
  \}

  function! LightLineMode()
    return
      \ &ft == 'unite' ? 'Unite' :
      \ winwidth(0) > 60 ? lightline#mode() : ''
  endfunction
'''
