#File seacher for unite
[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

#Copy history searcher for unite
[[plugins]]
repo = 'Shougo/neoyank.vim'
on_path = '.*'

#Useful vim interface provider
[[plugins]]
repo = 'Shougo/unite.vim'
depends = ['neomru.vim', 'neoyank.vim']
hook_add = '''
  let g:unite_force_overwrite_statusline = 0
  let g:unite_source_history_yank_enable = 1
  let g:unite_source_history_yank_limit = 100
  let g:unite_source_file_mru_limit = 200
  nnoremap <silent> <Space>uy :<C-u>Unite history/yank<CR>
  nnoremap <silent> <Space>uf :<C-u>Unite file<CR>
  nnoremap <silent> <Space>ur :<C-u>Unite file_rec<CR>
  nnoremap <silent> <Space>uu :<C-u>Unite buffer file_mru<CR>
  nnoremap <silent> <Space>um :<C-u>Unite file_mru<CR>
  nnoremap <silent> <Space>ub :<C-u>Unite buffer<CR>
  augroup MyAutoCmd
    autocmd FileType unite nnoremap <silent><buffer><expr> <C-k> unite#do_action('split')
    autocmd FileType unite inoremap <silent><buffer><expr> <C-k> unite#do_action('split')
    autocmd FileType unite nnoremap <silent><buffer><expr> <C-h> unite#do_action('vsplit')
    autocmd FileType unite inoremap <silent><buffer><expr> <C-h> unite#do_action('vsplit')
  augroup END
'''

#Filer
[[plugins]]
repo = 'scrooloose/nerdtree'
on_path = '.*'
hook_source = '''
  command NT NERDTree
'''

#Tester for the writing/opening script
[[plugins]]
repo = 'thinca/vim-quickrun'
on_path = '.*'
hook_source = '''
  command QR QuickRun
'''

#All about "surroundings"
[[plugins]]
repo = 'tpope/vim-surround'
on_path = '.*'

#Auto-complete for open-close pair of characters
[[plugins]]
repo = 'Townk/vim-autoclose'
on_path = '.*'

#Auto-complete for if/def-end pair of characters in Ruby, bash, zsh, VB, C/C++ preprocessor, Lua, Elixir, Haskell, Objective-C, Matlab, Crystal, Make, Verilog and Jinja templates
[[plugins]]
repo = 'tpope/vim-endwise'
on_event = 'InsertEnter'

#A useful vim window size controller
[[plugins]]
repo = 'simeji/winresizer'
on_event = 'WinNew'
hook_add = '''
  let g:winresizer_start_key = '<C-f>'
  let g:winresizer_vert_resize = 1
  let g:winresizer_horiz_resize = 1
'''

#A simple, easy-to-use vim alignment plugin
[[plugins]]
repo = 'junegunn/vim-easy-align'
on_path = '.*'
hook_add = '''
  xmap ga <Plug>(EasyAlign)
  nmap ga <Plug>(EasyAlign)
'''

#A viewer for markdown
[[plugins]]
repo = 'kannokanno/previm'
on_ft = 'markdown'
hook_add = '''
  let g:previm_enable_realtime = 1
  let g:previm_open_cmd = 'open -a "Google Chrome"'
  command PO PrevimOpen
'''

#An automatic table creator & formatter
[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_ft = 'markdown'
hook_add = '''
  let g:table_mode_corner = '|'
  command TT TableModeToggle
'''

#Auto compiler for latex
[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'
hook_add = '''
  let g:vimtex_compiler_latexmk_engines = {'_': '-pdfdvi'}
  let g:vimtex_view_method= 'skim'
  let g:vimtex_quickfix_ignore_filters = []
'''
hook_source = '''
  if empty(v:servername) && exists('*remote_startserver')
    call remote_startserver('VIM')
  endif
'''
